# Tokens

token ::=
    | ident
    | int_lit
    | global_name
    | local_name
    | label
    | "(" | ")" | "{" | "}" | "[" | "]"
    | "," | "="
    | space
    | comment
ident ::= [a-zA-Z$._-][a-zA-Z0-9$._-]*
space ::= [ \t\n\r\0]+
comment ::= ";" [^\n\r]* | "/*" .*? "*/"

# Syntax

program ::= func*

val_ty ::=
    | int_ty
    | ptr_ty
    | struct_ty
    | "[" int_lit "x" val_ty "]"
int_ty ::= "i16"
ptr_ty ::= "ptr"
struct_ty ::= "{" val_ty* "}"
bool_ty ::= "i1"

lit ::= int_lit | ptr_lit | bool_lit
int_lit ::= -?[0-9]+
ptr_lit ::= "null"
bool_lit ::= "0" | "1"

global_name ::= "@" name
local_name ::= "%" name
label ::= name ":"
name ::= ident | [0-9]+

val ::= local_name | int_lit | ptr_lit
ptr_val ::= local_name | ptr_lit
bool_val ::= local_name | bool_lit

func ::= "define" val_ty global_name params "{" bb* "}"
params ::= "(" (param ",")* param? ")"
param ::= val_ty local_name
args ::= "(" (arg ",")* arg? ")"
arg ::= val_ty val
bb ::= label inst* inst_term

inst ::=
    | local_name "=" arith int_ty val "," val
    | local_name "=" "extractvalue" struct_ty val "," int_lit ("," int_lit)*
    | local_name "=" "insertvalue" struct_ty val "," val_ty val "," int_lit ("," int_lit)*
    | local_name "=" "alloca" val_ty ("," int_ty val)?
    | local_name "=" "load" val_ty "," ptr_ty ptr_val
    | "store" val_ty val "," ptr_ty ptr_val
    | local_name "=" "icmp" cond bool_ty val "," val
    | local_name "=" "phi" val_ty "[" val "," local_name "]" ("," "[" val "," local_name "]")*
    | local_name "=" "call" val_ty global_name args
arith ::=
    | "add" | "sub" | "mul"
    | "udiv" | "sdiv" | "urem" | "srem"
    | "shl" | "lshr" | "ashr"
    | "and" | "or" | "xor"

inst_term ::=
    | "ret" val_ty val
    | "br" bool_ty cond "," "label" local_name "," "label" local_name
    | "br" "label" local_name

cond ::=
    | "eq" | "ne"
    | "ugt" | "uge" | "ult" | "ule"
    | "sgt" | "sge" | "slt" | "sle"
