val_ty ::=
    | int_ty
    | ptr_ty
    | struct_ty
    | "[" int_lit "x" val_ty "]"
int_ty ::= "i16"
ptr_ty ::= "ptr"
struct_ty ::= "{" val_ty* "}"
bool_ty ::= "i1"

lit ::= int_lit | ptr_lit | bool_lit
int_lit ::= -?[1-9][0-9]* | -?0x[0-9a-fA-F]+ | -?0b[01]+
ptr_lit ::= "null"
bool_lit ::= "0" | "1"

val_name ::= "%" ## ident
func_name ::= "@" ## ident
bb_def ::= ident ## ":"
bb_ref ::= "label" ident
bb_name ::= "%" ## ident
ident ::= \.?[a-zA-Z_](\.?[a-zA-Z0-9_])*

val ::= val_name | int_lit | ptr_lit
ptr_val ::= val_name | ptr_lit
bool_val ::= val_name | bool_lit

func ::= "define" val_ty func_name params "{" bb* "}"
params ::= "(" (param ",")* param? ")"
param ::= val_ty val_name
args ::= "(" (arg ",")* arg? ")"
arg ::= val_ty val
bb ::= bb_def inst* inst_term

inst ::=
    | val_name "=" arith int_ty val "," val
    | val_name "=" "extractvalue" struct_ty val "," int_lit ("," int_lit)*
    | val_name "=" "insertvalue" struct_ty val "," val_ty val "," int_lit ("," int_lit)*
    | val_name "=" "alloca" val_ty ("," int_ty val)?
    | val_name "=" "load" val_ty "," ptr_ty ptr_val
    | "store" val_ty val "," ptr_ty ptr_val
    | val_name "=" "icmp" cond bool_ty val "," val
    | val_name "=" "phi" val_ty "[" val "," bb_name "]" ("," "[" val "," bb_name "]")*
    | val_name "=" "call" val_ty func_name args
arith ::=
    | "add" | "sub" | "mul"
    | "udiv" | "sdiv" | "urem" | "srem"
    | "shl" | "lshr" | "ashr"
    | "and" | "or" | "xor"

inst_term ::=
    | "ret" val_ty val
    | "br" bool_ty cond "," bb_ref "," bb_ref
    | "br" bb_ref

cond ::=
    | "eq" | "ne"
    | "ugt" | "uge" | "ult" | "ule"
    | "sgt" | "sge" | "slt" | "sle"
