# LLVM IR subset used by Mini-Alive

## Tokens

token ::=
    | ident
    | int_lit
    | global_var
    | local_var
    | label
    | "(" | ")" | "{" | "}" | "[" | "]"
    | "," | "="
ignored ::=
    | space
    | comment

ident ::= [a-zA-Z$._-][a-zA-Z0-9$._-]*
space ::= [ \t\n\r\0]+
comment ::= ";" [^\n\r]* | "/*" .*? "*/"

## Syntax

program ::= global*
global ::= func_define | func_declare

type ::= int_ty | ptr_ty | struct_ty | array_ty
int_ty ::= "i16"
ptr_ty ::= "ptr"
struct_ty ::= "{" (type ("," type)*)? "}"
array_ty ::= "[" int_lit "x" type "]"
bool_ty ::= "i1"

lit ::= int_lit | ptr_lit | struct_lit | array_lit | bool_lit
int_lit ::= -?[0-9]+
ptr_lit ::= "null"
struct_lit ::= "{" (type lit ("," type lit)*)? "}"
array_lit ::= "[" (type lit ("," type lit)*)? "]"
bool_lit ::= "0" | "1"

global_var ::= "@" ## var
local_var ::= "%" ## var
label ::= var ## ":"
var ::= ident | [0-9]+

val ::= local_var | int_lit | ptr_lit | struct_lit | array_lit
bool_val ::= local_var | bool_lit

func_define ::= "define" type global_var params "{" (entry_bb bb*)? "}"
func_declare ::= "declare" type global_var params

params ::= "(" (param ("," param)*)? ")"
param ::= type local_var?
args ::= "(" (arg ("," arg)*)? ")"
arg ::= type val
entry_bb ::= label? inst* inst_term
bb ::= label inst* inst_term

inst ::=
    | local_var "=" arith int_ty val "," val
    | local_var "=" "extractvalue" struct_ty val "," int_lit ("," int_lit)*
    | local_var "=" "insertvalue" struct_ty val "," type val "," int_lit ("," int_lit)*
    | local_var "=" "alloca" type ("," int_ty val)?
    | local_var "=" "load" type "," ptr_ty val ("," "align" int_lit)?
    | "store" type val "," ptr_ty val ("," "align" int_lit)?
    | local_var "=" "icmp" cond type val "," val
    | local_var "=" "phi" type "[" val "," local_var "]" ("," "[" val "," local_var "]")*
    | local_var "=" "call" type global_var args
arith ::=
    | "add" | "sub" | "mul"
    | "udiv" | "sdiv" | "urem" | "srem"
    | "shl" | "lshr" | "ashr"
    | "and" | "or" | "xor"

inst_term ::=
    | "ret" type val
    | "br" "label" local_var
    | "br" bool_ty bool_val "," "label" local_var "," "label" local_var

cond ::=
    | "eq" | "ne"
    | "ugt" | "uge" | "ult" | "ule"
    | "sgt" | "sge" | "slt" | "sle"
